name: Docker Image PHP-FPM
on:
  schedule:
    - cron: "0 6 1 * *" # 6 AM UTC on 1st day of month
  push:
    paths:
      - version
      - images/.trigger
      - images/php-fpm/**
      - .github/workflows/*php-fpm*

jobs:
  php-fpm:
    name: PHP-FPM
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build php-fpm:${{ matrix.version }}
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}

      - name: Build php-fpm:${{ matrix.version }}-blackfire
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/blackfire/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-blackfire

      - name: Build php-fpm:${{ matrix.version }}-debug
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/debug/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-debug

      - name: Build php-fpm:${{ matrix.version }}-xdebug3
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/xdebug3/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-xdebug3

  magento1:
    name: PHP-FPM (${{ matrix.version }}) Magento1
    runs-on: ubuntu-latest
    needs: php-fpm

    strategy:
      fail-fast: false
      matrix:
        version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build php-fpm:${{ matrix.version }}-magento1
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/magento1/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-magento1

      - name: Build php-fpm:${{ matrix.version }}-magento1-blackfire
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/magento1/blackfire/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-magento1-blackfire

      - name: Build php-fpm:${{ matrix.version }}-magento1-debug
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/magento1/debug/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-magento1-debug

      - name: Build php-fpm:${{ matrix.version }}-magento1-xdebug3
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/magento1/xdebug3/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-magento1-xdebug3

  magento2:
    name: PHP-FPM (${{ matrix.version }}) Magento2
    runs-on: ubuntu-latest
    needs: php-fpm

    strategy:
      fail-fast: false
      matrix:
        version:
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Build php-fpm:${{ matrix.version }}-magento2
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/magento2/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-magento2

      - name: Build php-fpm:${{ matrix.version }}-magento2-blackfire
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/magento2/blackfire/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-magento2-blackfire

      - name: Build php-fpm:${{ matrix.version }}-magento2-debug
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/magento2/debug/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-magento2-debug

      - name: Build php-fpm:${{ matrix.version }}-magento2-xdebug3
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/context
          file: images/php-fpm/magento2/xdebug3/Dockerfile
          platforms: linux/amd64
          build-args: PHP_VERSION=${{ matrix.version }}
          push: ${{ github.ref == 'refs/heads/develop' && !env.ACT }}
          tags: docker.io/wardenenv/php-fpm:${{ matrix.version }}-magento2-xdebug3
